### ISSUE TITLE
Machinegun effect applied for sword

### ISSUE THREAD

**Issue by yncat** [munawarb/Treasure-Hunt#15]
Version 4.45
When you hold down spacebar with your sword equipped, you swing it so quickly like a machinegun.

**Comment by munawarb** [comment]
Hi @yncat , This is the intended behavior. But I can definitely slow it down a little.

**Comment by yncat** [comment]
Thanks for your answer. If it's intended, it may be better to slow it down to a realistic speed as you mentioned. It's just a suggestion though.
