### ISSUE TITLE
Latest treasure hunt version do not start in win xp

### ISSUE THREAD

**Issue by ghost** [munawarb/Treasure-Hunt#8]
Hello,

If I run th.exe I get the following error message:

"th.exe is not real win32 application"

Previous version workt ok.

thank you

Kari Uro

**Comment by munawarb** [comment]
Hi @karijuro , Are you running a 32-bit or 64-bit system?

I've upgraded Treasure Hunt to the latest .NET Framework and this could be causing issues on XP.

**Comment by ghost** [comment]
> Hi @karijuro , Are you running a 32-bit or 64-bit system?
> 
> I've upgraded Treasure Hunt to the latest .NET Framework and this could be causing issues on XP.

Hello,

I am using 32 bit version

Kari Uro

**Comment by ghost** [comment]
Hello again,

I updated to latest .net framework, but it do not fix the problem. Same error message after update.

Kari Uro

**Comment by munawarb** [comment]
Hi @karijuro , I'm going to see about making the next version 32-bit only instead of being architecture-agnostic. That might fix the problem. Nowadays very few people run 32-bit OS's so I didn't think about this.

**Comment by ghost** [comment]
Hello,

Thank you for your reply.

Three-d-vilocity has also the same problem. But if you can first make 32 bit version of treasure hunt, and it runs in 32 bit win xp,. You can start the same process with three-d-vilocity.

Sorry my bad english

Kari Uro

**Comment by munawarb** [comment]
Hi @karijuro , TDV is compiled for 32-bit systems so I'm not sure why it wouldn't work. Either way, yes, we'll test it together on your system. I'll post here when I've put out the next version of Treasure Hunt and you can try it out.

**Comment by ghost** [comment]
Hello,

I had found a reason why the tdv is not runing under win xp. Tdv is not runing because it is using .net framework 4.6 and win xp supports only 4.03. .net framework 4.5 and later is not supported.
 Check the link below for more information.
Kari Uro
[https://blogs.msdn.microsoft.com/dotnet/p/dotnet45xp/](url)

**Comment by munawarb** [comment]
Thanks for this information. I'm not able to downgrade the project 
because I'm using 4.6-specific features in the latest build. The 
unreleased build is also linking against BPCSharedComponent.dll which is 
a 4.6 dll.

**Comment by munawarb** [comment]
Treasure Hunt no longer supports XP; I need to note this in the readme.
